// Sample work shown when the office is opened without a live server.
export const POOL_PT = {
  elead: ['Revisar a caixa de entrada da noite e encaminhar 40 e-mails', 'Revisar o tom de 6 respostas a clientes', 'Resumir a caixa de entrada da semana para a gestão', 'Atualizar os modelos de resposta', 'Escalar 2 conversas para a gestão'],
  cmail: ['Responder à dúvida de {co} sobre o escopo', 'Enviar a {co} o resumo da reunião inicial', 'Responder a 9 e-mails de clientes recebidos à noite', 'Redigir o aviso de reajuste de preços', 'Cobrar a aprovação do briefing de {co}'],
  imail: ['Fazer a triagem de 14 e-mails internos', 'Compartilhar os números da semana', 'Responder à equipe sobre o plano do terceiro trimestre', 'Resumir uma conversa de 40 mensagens', 'Marcar a revisão do cliente no calendário'],
  vmail: ['Resumir a revisão do acordo de serviço do fornecedor', 'Responder ao fornecedor de SMS sobre o plano', 'Pedir cotação ao fornecedor de impressos', 'Cobrar o relatório da falha de hospedagem', 'Confirmar a data de renovação do fornecedor'],
  kmail: ['Responder à dúvida do designer sobre a fatura', 'Enviar o briefing ao redator', 'Confirmar as horas do prestador nesta semana', 'Cobrar uma estimativa do desenvolvedor', 'Responder ao prestador de vídeo sobre o prazo'],
  lexi: ['Revisar os dados reunidos à noite antes da equipe de vendas', 'Montar as listas de ligações de hoje', 'Retomar {n} negociações sem contato há 14 dias', 'Preparar a revisão semanal do funil de vendas', 'Ajustar o perfil de cliente ideal com a prospecção'],
  enzo: ['Enriquecer {n} cadastros recebidos à noite', 'Verificar os telefones do lote australiano', 'Completar o porte de 12 empresas', 'Pontuar os leads da manhã para a liderança de vendas', 'Reprocessar 3 enriquecimentos que falharam'],
  ilm: ['Qualificar {n} leads recebidos pelo site', 'Encaminhar 6 leads promissores à equipe', 'Responder a {co} em até uma hora', 'Agendar uma conversa inicial com {co}', 'Limpar a fila de leads: 12 duplicados'],
  pros: ['Encontrar {n} empresas do setor de {segment} para prospecção', 'Pontuar 40 potenciais clientes conforme o perfil ideal', 'Montar a lista de ligações de amanhã', 'Conferir novos contatos com a base de clientes', 'Verificar os telefones do novo lote'],
  piper: ['Preparar proposta para um potencial cliente com 40 usuários', 'Atualizar o modelo de proposta do plano Growth', 'Preparar opções de preço para {co}', 'Montar material de acompanhamento da proposta de {co}', 'Criar link de assinatura eletrônica para a proposta de {co}'],
  folo: ['Acompanhar {n} cotações enviadas na semana passada', 'Retomar contato com 8 leads frios', 'Registrar resultados das ligações no CRM', 'Lembrar negócios parados há 14 dias', 'Agendar uma demonstração para {co}'],
  mlead: ['Revisar o conteúdo da semana antes de publicar', 'Direcionar US$ 50 por dia ao anúncio vencedor', 'Planejar os reels da próxima semana', 'Resumir o marketing da semana para a gestão', 'Pedir à pesquisa um ângulo para {segment}'],
  riley: ['Pesquisar 49 fontes pela manhã', 'Comparar os preços dos concorrentes da semana', 'Separar 3 dados para a newsletter', 'Preparar tendências para a liderança de vendas', 'Ler 6 avaliações de compradores em busca de ideias'],
  newt: ['Redigir a newsletter de setembro', 'Testar assuntos A/B para a edição 32', 'Registrar os resultados da edição 31', 'Revisar o segundo e-mail de boas-vindas', 'Limpar 40 inscritos com e-mails inválidos'],
  gfx: ['Criar cartões com citações para a página de preços', 'Exportar formatos story e quadrado da identidade visual', 'Criar miniatura para o reel da regra das 10h', 'Propor 3 capas de carrossel', 'Adaptar a peça do anúncio para 4:5'],
  ada: ['Atualizar o conjunto de anúncios com queda de desempenho', 'Lançar 4 versões do anúncio sobre receio de ligar', 'Preparar o relatório diário de gastos', 'Direcionar US$ 50 por dia ao anúncio vencedor', 'Excluir clientes atuais da segmentação'],
  iggy: ['Escrever a abertura do carrossel', 'Registrar o desempenho das aberturas no guia', 'Agendar 3 publicações para a semana', 'Responder a 14 mensagens diretas', 'Encurtar a legenda do reel da regra das 10h'],
  vid: ['Renderizar o reel da regra das 10h com legendas', 'Criar um teaser de 15 segundos da demonstração', 'Renderizar versões 4:5 dos anúncios', 'Revisar as legendas do webinar', 'Ajustar cor e legendas do reel da fundadora', 'Renderizar a demonstração de 45 segundos'],
  olead: ['Revisar contratos e pontos de atenção da semana', 'Cobrar {n} renovações pendentes de fornecedores', 'Priorizar as descobertas da inteligência', 'Resumir as operações da semana para a gestão', 'Preparar as seções do relatório para a diretoria'],
  scout: ['Comparar mudanças na página de preços do concorrente', 'Ler avaliações dos 3 principais concorrentes no G2', 'Redigir nota sobre aumento de preço do concorrente', 'Atualizar o mapa do mercado do terceiro trimestre', 'Acompanhar a página de lançamento do concorrente'],
  legal: ['Revisar o acordo alterado e 2 cláusulas', 'Preparar o contrato do designer prestador', 'Revisar anualmente a política de privacidade', 'Marcar alterações nos termos de {co}', 'Conferir a cláusula de preço fixo'],
  comply: ['Comparar mudanças na página de regulamentação australiana', 'Auditar o texto de consentimento dos formulários', 'Conferir a retenção de dados em 3 sistemas', 'Preparar a lista trimestral de conformidade', 'Revisar o aviso de cookies'],
  report: ['Preparar relatório semanal para a diretoria em 6 seções', 'Consolidar os indicadores mensais', 'Relatar a perda de clientes por grupo de entrada', 'Relatar o nível de serviço das entregas', 'Resumir a atividade dos representantes'],
  dash: ['Atualizar o painel de vendas', 'Adicionar indicador de entregas no prazo', 'Corrigir o período do gráfico de receita', 'Criar visualização do tempo de resposta da caixa de entrada', 'Verificar semanalmente a saúde dos painéis'],
  alead: ['Revisar a posição de caixa da semana', 'Aprovar os pagamentos dos prestadores', 'Preparar o fechamento do mês', 'Revisar os preços dos fornecedores', 'Projetar o caixa das próximas 8 semanas'],
  invo: ['Emitir {n} faturas nesta semana', 'Cobrar 3 faturas vencidas', 'Emitir nota de crédito para {co}', 'Faturar US$ 840 para {co}', 'Enviar o segundo de 3 lembretes a {co}'],
  apay: ['Conferir as cobranças de cartão de hoje', 'Auditar a fatura 218 do prestador com o contrato', 'Agendar os pagamentos dos prestadores', 'Sinalizar assinaturas sobrepostas', 'Conferir o plano do fornecedor de SMS'],
  recon: ['Conciliar 14 pagamentos e sinalizar 2', 'Conciliar o extrato bancário do fechamento', 'Conciliar repasses da Stripe com faturas', 'Resolver 2 taxas sem correspondência', 'Fechar a conferência do extrato do cartão'],
  dlead: ['Revisar os riscos de 12 projetos ativos', 'Resumir as entregas da semana para a gestão', 'Replanejar os prazos de {co}', 'Aprovar a entrega de {co}', 'Definir a equipe do projeto de {co}'],
  pco: ['Atualizar o plano do projeto de {co}', 'Mover 3 marcos após mudança de escopo', 'Cobrar 2 aprovações atrasadas de clientes', 'Agendar a revisão de {co}', 'Registrar as horas da semana por projeto'],
  qa: ['Testar a entrega do site de {co}', 'Conferir erros no relatório de {co}', 'Testar o acesso ao portal do cliente', 'Revisar materiais conforme as regras da marca', 'Testar novamente o formulário de reservas'],
  crep: ['Preparar relatório de setembro para {co}', 'Montar relatórios mensais para 14 clientes', 'Adicionar os resultados ao relatório de {co}', 'Enviar o relatório de {co} com 2 alertas', 'Criar gráfico dos leads de {co}'],
  cass: ['Sincronizar os materiais de {co} com o portal', 'Organizar a biblioteca de materiais de {co}', 'Exportar logotipos em 4 formatos', 'Arquivar os arquivos concluídos de {co}', 'Organizar 60 materiais por campanha'],
  dasst: ['Criar modelos para redes sociais de {co}', 'Adaptar 6 banners de {co}', 'Fazer protótipo da página de destino de {co}', 'Preparar o guia de marca de {co}', 'Criar a capa do relatório de {co}'],
  ona: ['Preparar a reunião inicial de {co}', 'Preparar a lista de integração de {co}', 'Configurar o portal do cliente {co}', 'Apresentar o primeiro relatório a {co}', 'Fazer contato com {co} no sétimo dia'],
};

export const KEYS_PT = {
  elead: ['resumo', 'modelo', 'escalar', 'caixa de entrada'], cmail: ['cliente', 'responder', 'escopo'],
  imail: ['equipe', 'interno', 'calendário', 'conversa'], vmail: ['fornecedor', 'renovação', 'cotação'],
  kmail: ['prestador', 'freelancer', 'designer', 'redator'], lexi: ['funil', 'vendas', 'negociação'],
  enzo: ['enriquecer', 'cadastro', 'verificar dados'], ilm: ['lead recebido', 'qualificar', 'encaminhar'],
  pros: ['prospecção', 'prospectar', 'lista de empresas'], piper: ['proposta', 'preço', 'cotação'],
  folo: ['acompanhar', 'retomar', 'demonstração'], mlead: ['plano de conteúdo', 'marketing', 'orçamento'],
  riley: ['pesquisa', 'tendência', 'fonte'], newt: ['newsletter', 'inscrito', 'boas-vindas'],
  gfx: ['design', 'gráfico', 'miniatura', 'imagem', 'banner', 'capa'], ada: ['anúncio', 'campanha', 'gasto'],
  iggy: ['instagram', 'publicação', 'carrossel'], vid: ['vídeo', 'reel', 'editar', 'legenda'],
  olead: ['operações', 'renovação', 'diretoria'], scout: ['concorrente', 'mercado', 'inteligência'],
  legal: ['contrato', 'jurídico', 'cláusula'], comply: ['conformidade', 'regulação', 'consentimento', 'privacidade'],
  report: ['relatório', 'indicador', 'resumo'], dash: ['painel', 'gráfico', 'métrica'],
  alead: ['caixa', 'previsão', 'fechamento'], invo: ['fatura', 'faturamento', 'vencida'],
  apay: ['pagamento', 'cobrança', 'conta a pagar'], recon: ['conciliar', 'conciliação', 'extrato'],
  dlead: ['risco', 'prazo', 'entrega'], pco: ['plano', 'marco', 'agendar'],
  qa: ['teste', 'qualidade', 'erro'], crep: ['relatório do cliente', 'resultados'],
  cass: ['material', 'arquivo', 'portal'], dasst: ['design', 'modelo', 'banner'],
  ona: ['integração', 'reunião inicial', 'boas-vindas'],
};

export const CHAINS_PT = [
  ['Planejar os reels da próxima semana', 'Pesquisar ângulos para os reels', 'Escrever as aberturas dos reels'],
  ['Revisar o acordo alterado de {co}', 'Decidir sobre a cláusula de {co} e escalar se necessário'],
  ['Pesquisar ângulos para o próximo reel', 'Escrever o roteiro do reel com base na pesquisa', 'Editar e renderizar o reel com legendas'],
  ['Criar peças para os novos anúncios de {segment}', 'Lançar 4 versões dos anúncios de {segment}'],
  ['Montar lista de potenciais clientes de {segment}', 'Qualificar a lista de {segment} e encaminhar os leads promissores', 'Revisar os leads encaminhados com a equipe'],
  ['Enriquecer os cadastros recebidos à noite', 'Encaminhar os leads enriquecidos à equipe'],
  ['Lead qualificado: {co} quer uma cotação', 'Preparar proposta para {co}', 'Conferir os termos de {co}'],
  ['Proposta aceita por {co}', 'Integrar {co}: reunião inicial', 'Criar o plano do projeto de {co}'],
  ['Pedido de mudança de escopo de {co}', 'Replanejar os marcos de {co}', 'Atualizar o relatório de status de {co}'],
  ['Criar os materiais de {co}', 'Revisar a qualidade dos materiais de {co}', 'Publicar os materiais de {co} no portal'],
  ['Detectada mudança de preço do concorrente; preparar nota', 'Atualizar a tabela de preços da proposta'],
  ['Emitir as faturas desta semana', 'Conciliar pagamentos com as novas faturas'],
  ['Consolidar os indicadores mensais', 'Atualizar o painel de indicadores', 'Incluir os indicadores no fechamento do mês'],
  ['Cotação de fornecedor recebida para {co}', 'Conferir a cotação do fornecedor com o orçamento'],
  ['Dúvida do designer sobre a fatura do prestador', 'Conferir a fatura do prestador com o contrato'],
  ['Equipe pede os números do terceiro trimestre', 'Atualizar o painel do terceiro trimestre'],
  ['Relatório de setembro pronto para {co}', 'Enviar o relatório de {co} com um resumo'],
];

export const APPROVAL_ASKS_PT = {
  emails: ['Enviar aviso de reajuste a 120 clientes — rascunho anexo', 'Responder à disputa com o prestador — rascunho anexo'],
  delivery: ['Enviar os relatórios de setembro a 14 clientes', 'Publicar os materiais de marca no portal do cliente'],
  sales: ['Enviar SMS para retomar contato com 214 leads frios', 'Mover 8 leads empresariais para a fila da equipe'],
  marketing: ['Lançar 4 versões do anúncio na Meta — orçamento de US$ 120/dia', 'Publicar reel sobre ligações frias no Instagram'],
  ops: ['Enviar proposta em PDF ao Ridgeline Property Group', 'Aprovar o acordo alterado da Kea Logistics — 2 cláusulas sinalizadas'],
  fin: ['A fatura 218 diverge do contrato — reter para revisão?', 'Baixar US$ 180 em taxas de cartão não conciliadas'],
};
export const APPROVAL_BY_AGENT_PT = {
  cmail: 'Enviar aviso de reajuste a 120 clientes — rascunho anexo',
  vmail: 'Aceitar a revisão do acordo de serviço do fornecedor — 2 mudanças sinalizadas',
  crep: 'Enviar relatórios de setembro a 14 clientes — 2 precisam de ligação',
  qa: 'Aprovar a entrega do site — 2 problemas menores anotados',
  dlead: 'Prorrogar o projeto Ridgeline por uma semana a pedido do cliente',
  apay: 'A fatura 218 do prestador está US$ 350 acima do contrato — reter pagamento e questionar?',
  piper: 'Enviar proposta ao Ridgeline Property Group — 12 usuários, plano Growth',
  iggy: 'Publicar reel sobre a regra das 10h no Instagram — roteiro anexo',
  vid: 'Enviar vídeo demonstrativo de 45 segundos — legendas incluídas, versão 2 anexa',
  ada: 'Aumentar o orçamento do anúncio para US$ 180/dia — custo por aquisição de US$ 29',
  mlead: 'Aprovar o plano de conteúdo de outubro — 12 reels, 2 newsletters e 1 atualização de anúncio',
  olead: 'Aprovar a lista operacional do quarto trimestre — 3 renovações de fornecedores',
  newt: 'Enviar a newsletter de agosto a 3.400 inscritos — versão 3 anexa',
  scout: 'Aprovar comparação com a CallForge — nota anexa',
  enzo: 'Comprar 500 créditos FullEnrich — o lote atual acaba amanhã',
};
export const WORKLINES_PT = {
  emails: ['▸ redigindo resposta sobre escopo do cliente', '▸ conversa com fornecedor: revisão do acordo resumida', '▸ 14 e-mails internos triados · 3 para a gestão', '▸ dúvida sobre fatura do prestador respondida'],
  delivery: ['▸ relatório do cliente: pacote de setembro 9/14', '▸ revisão de qualidade da entrega do site · 2 notas', '▸ biblioteca de materiais sincronizada com o portal', '▸ plano do projeto: 3 marcos movidos'],
  sales: ['▸ enriquecendo lead — Summit HVAC', '▸ 6 leads encaminhados à equipe (fila de 4,2 h)', '▸ 32 contatos verificados · 91% válidos', '▸ mensagem de integração enviada — Bay Plumbing'],
  marketing: ['▸ redigindo abertura do reel sobre ligações frias', '▸ anúncios Meta: 4 versões para revisão', '▸ segundo de 5 blocos da newsletter escrito', '▸ exportação da marca: story e quadrado', '▸ renderizando reel versão 2 com legendas'],
  ops: ['▸ proposta em PDF criada — Ridgeline Group', '▸ análise de preços do concorrente DialAxis', '▸ cláusula 7.2 do acordo sinalizada — limite de responsabilidade', '▸ página WorkSafe AU mudou · comparando', '▸ relatório semanal: 4 de 6 seções concluídas'],
  fin: ['▸ conciliando 14 pagamentos · 2 sinalizados', '▸ fatura 218 vs. contrato — divergência de preço', '▸ fatura emitida — Summit HVAC, US$ 840', '▸ segundo de 3 lembretes enviado — Alpine Freight'],
  brain: ['▸ indexando as notas — 1.204 registros', '▸ respondendo a consulta de inteligência', '▸ reunião agendada: enzo × tess'],
};
